In [4]:
import numpy as np
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([3,1,1])
matrix = np.column_stack((a,b,c))
print(matrix)
print(type(matrix))

matrix2 = np.array([a,b,c])
print(matrix2)

A = np.array([[2,3],[4,2],[2,2]])
B = np.array([[4,2],[4,6]])
x = np.dot(A,B)
print(x)

[[1 2 3]
 [2 2 1]
 [3 2 1]]
<class 'numpy.ndarray'>
[[1 2 3]
 [2 2 2]
 [3 1 1]]
[[20 22]
 [24 20]
 [16 16]]


In [13]:
x = np.dot(A,B)


print(matrix)
print('\n-------------------------\n')
print(np.linalg.inv(matrix))

[[1 2 3]
 [2 2 1]
 [3 2 1]]

-------------------------

[[ 0.   -1.    1.  ]
 [-0.25  2.   -1.25]
 [ 0.5  -1.    0.5 ]]


In [14]:
inverse = np.linalg.inv(matrix)
print(np.dot(matrix, inverse))
print('\n-------------------------\n')
print(np.dot(inverse,matrix))

[[ 1.00000000e+00 -6.66133815e-16  5.55111512e-16]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]

-------------------------

[[ 1.00000000e+00 -4.44089210e-16 -2.22044605e-16]
 [ 6.66133815e-16  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00]]


In [16]:
import numpy as np

singular = np.array([[1, 2, 3], [1, 2, 3], [3, 3, 3]])

# Check if the matrix is singular
det = np.linalg.det(singular)

if det == 0:
    print("The matrix is singular, and its determinant is zero.")
else:
    inv = np.linalg.inv(singular)
    print("The matrix is non-singular, and its inverse is:")
    print(inv)


The matrix is singular, and its determinant is zero.


In [18]:
A = np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
b = np.array([[8],[-11],[-3]])
inv_A = np.linalg.inv(A)
print(np.dot(inv_A, b))

print(np.linalg.solve(A, b))

[[ 2.]
 [ 3.]
 [-1.]]
[[ 2.]
 [ 3.]
 [-1.]]
